# Generated by Django 5.2.7 on 2025-12-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(db_column='ca_IdCargo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='ca_NombreCargo', max_length=50, unique=True)),
                ('area', models.CharField(db_column='ca_Area', max_length=30)),
            ],
            options={
                'db_table': 'CARGO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(db_column='tu_IdTipoUsuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='tu_NombreTipoUsuario', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'TIPOUSUARIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='us_IdUsuario', primary_key=True, serialize=False)),
                ('cedula', models.CharField(db_column='us_Cedula', max_length=30, unique=True)),
                ('nombre', models.CharField(db_column='us_Nombre', max_length=50)),
                ('apellido', models.CharField(db_column='us_Apellido', max_length=50)),
                ('celular', models.CharField(blank=True, db_column='us_Celular', max_length=15, null=True)),
                ('correo', models.EmailField(blank=True, db_column='us_Correo', max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(db_column='us_FechaCreacion')),
                ('user', models.CharField(db_column='us_User', max_length=20, unique=True)),
                ('password', models.CharField(db_column='us_Password', max_length=20)),
            ],
            options={
                'db_table': 'USUARIO',
                'ordering': ['apellido', 'nombre'],
                'managed': False,
            },
        ),
    ]
