# Generated by Django 5.2.7 on 2026-01-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataQRFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prensa', models.IntegerField(blank=True, db_column='PRENSA', null=True)),
                ('molde', models.CharField(db_column='MOLDE', max_length=50)),
                ('alterno', models.CharField(blank=True, db_column='ALTERNO', max_length=50, null=True)),
                ('diametro', models.CharField(blank=True, db_column='DIAMETRO', max_length=50, null=True)),
                ('espiga', models.CharField(blank=True, db_column='ESPIGA', max_length=50, null=True)),
                ('profundidad', models.CharField(blank=True, db_column='PROFUNDIDAD', max_length=100, null=True)),
                ('maquina_principal', models.CharField(blank=True, db_column='MAQUINA_PRINCIPAL', max_length=50, null=True)),
                ('opcional', models.CharField(blank=True, db_column='OPCIONAL', max_length=50, null=True)),
                ('porta_pastillas', models.CharField(blank=True, db_column='PORTA_PASTILLAS', max_length=50, null=True)),
                ('piso', models.IntegerField(blank=True, db_column='PISO', null=True)),
                ('estanteria', models.CharField(blank=True, db_column='ESTANTERIA', max_length=50, null=True)),
                ('fila', models.IntegerField(blank=True, db_column='FILA', null=True)),
                ('columna', models.IntegerField(blank=True, db_column='COLUMNA', null=True)),
                ('posicion', models.IntegerField(blank=True, db_column='POSICION', null=True)),
                ('foto', models.IntegerField(blank=True, db_column='FOTO', null=True)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=100, null=True)),
                ('observaciones', models.CharField(blank=True, db_column='OBSERVACIONES', max_length=50, null=True)),
                ('estado', models.CharField(blank=True, db_column='ESTADO', max_length=50, null=True)),
                ('existencia_inventario', models.IntegerField(blank=True, db_column='EXISTENCIA_INVENTARIO', null=True)),
                ('ruta_imagen', models.CharField(blank=True, db_column='Ruta_Imagen', max_length=50, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_column='Fecha_Hora')),
                ('decode_status', models.CharField(blank=True, db_column='Decode_Status', max_length=50, null=True)),
                ('error', models.CharField(blank=True, db_column='Error', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Archivo de Datos QR',
                'verbose_name_plural': 'Archivos de Datos QR',
                'db_table': 'dataqrfile',
            },
        ),
    ]
