# Generated by Django 5.2.7 on 2026-01-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataqrfile',
            options={'managed': False, 'verbose_name': 'Sabana de datos qr', 'verbose_name_plural': 'Archivos de Datos QR'},
        ),
    ]
