# Generated by Django 5.2.7 on 2026-02-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0002_alter_dataqrfile_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dataqrfile',
            table='sabana_qr_files',
        ),
    ]
