"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
#Para ejecutar las variables del archivo .env (credenciales BD)
from dotenv import load_dotenv
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '10.1.2.14', 'localhost', '127.0.0.1', '10.1.2.180',
    '10.1.0.226', '10.1.1.14'
]


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',       # Disabled: admin UI disabled
    'django.contrib.auth',         # Enabled for Python model definitions & DRF/SimpleJWT compatibility
    'django.contrib.contenttypes', # Enabled for Django app registry & DRF compatibility
    # 'django.contrib.sessions',    # Disabled: stateless JWT API
    # 'django.contrib.messages',    # Disabled: relies on session middleware
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'app.herramental',
    'app.ipsl',
    'app.produccion',
    'app.usuarios',
    'app.documents',
    'app.posicion',
    'app.temp',
    # JWT: autenticación con tokens
    'rest_framework_simplejwt',
    # 'rest_framework_simplejwt.token_blacklist', # Disabled: requires auth_user table
    # App de autenticación personalizada
    'app.auth_app',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # 'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                # 'django.contrib.auth.context_processors.auth',
                # 'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': os.getenv('DATABASE_BD'),
        'USER': os.getenv('DATABASE_USER'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),
        'HOST': os.getenv('DATABASE_SERVER'),
        'PORT': os.getenv('DATABASE_PORT'),
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    }
}

# CORS settings
# https://pypi.org/project/django-cors-headers/

# Se utilizará solo estos orígenes para las solicitudes CORS.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5174",
    "http://10.1.0.62:5174", #IP Ethernet - Frontend - Karo
    "http://10.1.2.180:5174", #IP Wifi - Frontend - Karo
]

# Permitir todas las solicitudes CORS (solo para desarrollo)
CORS_ALLOW_ALL_ORIGINS = True # Desactivar en producción

# REST Framework settings
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators


""" AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
] """


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# URL que verá el navegador para acceder a los archivos multimedia (subidos por los usuarios)
# Ruta pública para acceder a los archivos multimedia, por ejemplo: http://localhost:8000/media/archivo.jpg
MEDIA_URL = '/media/'
# Ruta absoluta en el sistema de archivos donde se almacenarán los archivos multimedia subidos por los usuarios
MEDIA_ROOT = 'E:/FileServer/media' # Ruta absoluta en Windows

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# DJANGO REST FRAMEWORK — Configuración global -- Added 16/06/2026
# ==============================================================================
REST_FRAMEWORK = {
    # Permisos por defecto: AllowAny durante desarrollo o IsAuthenticated según configuración
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],

    # Autenticador JWT personalizado para rescatar objetos Usuario de la tabla USUARIO
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'app.auth_app.backends.UsuarioJWTAuthentication',
    ],
}
 
 
# ==============================================================================
# SIMPLE JWT — Configuración de tokens
# ==============================================================================
from datetime import timedelta
 
SIMPLE_JWT = {
    # Access Token: vida corta por seguridad.
    # Expira en 15 minutos, el frontend debe renovarlo con el refresh token.
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
 
    # Refresh Token: vida larga para no forzar login frecuente.
    # Expira en 7 días. Si el usuario no usa la app en 7 días, debe volver a loguear.
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
 
    # ROTATE_REFRESH_TOKENS: si es True, cada vez que se usa el refresh token
    # para obtener un nuevo access, también se genera un nuevo refresh token.
    # Más seguro pero requiere que el frontend guarde el nuevo refresh cada vez.
    # Lo dejamos en False para simplicidad inicial.
    'ROTATE_REFRESH_TOKENS': False,
 
    # BLACKLIST_AFTER_ROTATION: solo aplica si ROTATE es True.
    # Invalida el refresh token anterior después de rotar.
    'BLACKLIST_AFTER_ROTATION': True,
 
    # Algoritmo de firma del token (HS256 = HMAC con SHA-256)
    # Usa SECRET_KEY de Django como clave de firma.
    'ALGORITHM': 'HS256',
 
    # Nombre del header HTTP que debe incluir el token.
    # El frontend debe enviar: Authorization: Bearer <token>
    'AUTH_HEADER_TYPES': ('Bearer',),
 
    # Campo del modelo que se guarda en el token como identificador del usuario.
    # simplejwt buscará este campo para llamar a get_user() del backend.
    'USER_ID_FIELD': 'id',
 
    # Nombre del claim (clave) dentro del payload del JWT que guarda el user_id.
    'USER_ID_CLAIM': 'user_id',
}
 
 
# ==============================================================================
# AUTHENTICATION BACKENDS
# ==============================================================================
# Django recorre esta lista en orden al llamar authenticate().
# Nuestro backend personalizado valida contra la tabla USUARIO de negocio.
# ModelBackend (el default) valida contra auth_user; lo mantenemos como fallback
# para el panel de administración de Django.
# AUTHENTICATION_BACKENDS = [
#     # Primero: nuestro backend de negocio (tabla USUARIO)
#     #'app.auth_app.backends.UsuarioNegocioBackend',
#     # ModelBackend por defecto desactivado para evitar consultas a auth_user
#     # 'django.contrib.auth.backends.ModelBackend',
# ]

