# Generated by Django 5.2.7 on 2025-12-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(db_column='fa_IdFamilia', primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, db_column='fa_CodigoFamilia', max_length=4, null=True)),
                ('nombre', models.CharField(db_column='fa_NombreFamilia', max_length=15)),
            ],
            options={
                'db_table': 'FAMILIA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Herramental',
            fields=[
                ('id', models.AutoField(db_column='he_IdHerramental', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='he_NombreHerramental', max_length=15)),
                ('codigo', models.CharField(db_column='he_CodigoHerramental', max_length=4, unique=True)),
            ],
            options={
                'db_table': 'HERRAMENTAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoHerramental',
            fields=[
                ('id', models.AutoField(db_column='th_IdTipoHerramental', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='th_NombreTipoHerramental', max_length=15)),
                ('codigo', models.CharField(db_column='th_CodigoTipoHerramental', max_length=4, unique=True)),
            ],
            options={
                'db_table': 'TIPOHERRAMENTAL',
                'managed': False,
            },
        ),
    ]
