# Generated by Django 5.2.7 on 2026-01-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estadoHerramental',
            fields=[
                ('id', models.AutoField(db_column='eh_IdEstadoHerr', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='eh_NombreEstadoHrr', max_length=20)),
                ('descripcion', models.TextField(blank=True, db_column='eh_DescripcionEstadoHrr', null=True)),
            ],
            options={
                'db_table': 'ESTADOHERRAMENTAL',
                'managed': False,
            },
        ),
    ]
