# Generated by Django 5.2.7 on 2026-02-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramental', '0002_estadoherramental'),
    ]

    operations = [
        migrations.CreateModel(
            name='HerramentalEspecifico',
            fields=[
                ('hesp_IdHerramentalEspecifico', models.AutoField(db_column='hesp_IdHerramentalEspecifico', primary_key=True, serialize=False)),
                ('hesp_CodigoHerramental', models.CharField(db_column='hesp_CodigoHerramental', max_length=20, unique=True)),
                ('hesp_CodigoAlterno', models.CharField(blank=True, db_column='hesp_CodigoAlterno', max_length=15, null=True)),
                ('hesp_Descripcion1', models.TextField(blank=True, db_column='hesp_Descripcion1', null=True)),
                ('hesp_Descripcion2', models.TextField(blank=True, db_column='hesp_Descripcion2', null=True)),
                ('hesp_CantPieza', models.IntegerField(db_column='hesp_CantPieza')),
                ('hesp_Observacion', models.CharField(blank=True, db_column='hesp_Observacion', max_length=100, null=True)),
                ('hesp_FechaReparacion', models.DateTimeField(blank=True, db_column='hesp_FechaReparacion', null=True)),
                ('hesp_NumNariz', models.PositiveSmallIntegerField(blank=True, db_column='hesp_NumNariz', null=True)),
                ('hesp_NumCopas', models.PositiveSmallIntegerField(blank=True, db_column='hesp_NumCopas', null=True)),
                ('hesp_Radio', models.DecimalField(blank=True, db_column='hesp_Radio', decimal_places=4, max_digits=10, null=True)),
                ('hesp_Altura1', models.DecimalField(blank=True, db_column='hesp_Altura1', decimal_places=4, max_digits=10, null=True)),
                ('hesp_Altura2', models.DecimalField(blank=True, db_column='hesp_Altura2', decimal_places=4, max_digits=10, null=True)),
                ('hesp_Diametro', models.DecimalField(blank=True, db_column='hesp_Diametro', decimal_places=4, max_digits=10, null=True)),
                ('hesp_Ancho', models.DecimalField(blank=True, db_column='hesp_Ancho', decimal_places=4, max_digits=10, null=True)),
                ('hesp_Profundidad', models.DecimalField(blank=True, db_column='hesp_Profundidad', decimal_places=4, max_digits=10, null=True)),
                ('hesp_Grado', models.DecimalField(blank=True, db_column='hesp_Grato', decimal_places=4, max_digits=10, null=True)),
                ('hesp_ProfunRecogida', models.DecimalField(blank=True, db_column='hesp_ProfunRecogida', decimal_places=4, max_digits=10, null=True)),
                ('hesp_Largo', models.DecimalField(blank=True, db_column='hesp_Largo', decimal_places=4, max_digits=10, null=True)),
                ('hesp_A', models.DecimalField(blank=True, db_column='hesp_A', decimal_places=4, max_digits=10, null=True)),
                ('hesp_B', models.DecimalField(blank=True, db_column='hesp_B', decimal_places=4, max_digits=10, null=True)),
                ('hesp_C', models.DecimalField(blank=True, db_column='hesp_C', decimal_places=4, max_digits=10, null=True)),
                ('hesp_D', models.DecimalField(blank=True, db_column='hesp_D', decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'HERRAMENTALESPECIFICO',
            },
        ),
    ]
