# Generated by Django 5.2.7 on 2026-03-05 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramental', '0003_herramentalespecifico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estanteria',
            fields=[
                ('es_IdEstanteria', models.AutoField(db_column='es_IdEstanteria', primary_key=True, serialize=False)),
                ('es_NombreEstanteria', models.CharField(db_column='es_NombreEstanteria', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estantería',
                'verbose_name_plural': 'Estanterías',
                'db_table': 'ESTANTERIA',
                'ordering': ['es_NombreEstanteria'],
            },
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('pi_IdPiso', models.AutoField(db_column='pi_IdPiso', primary_key=True, serialize=False)),
                ('pi_NumeroPiso', models.CharField(db_column='pi_NumeroPiso', max_length=10, unique=True)),
                ('pi_DescripcionPiso', models.CharField(blank=True, db_column='pi_DescripcionPiso', max_length=255, null=True)),
            ],
            options={
                'db_table': 'PISO',
            },
        ),
        migrations.AddField(
            model_name='herramentalespecifico',
            name='hesp_IdActividad',
            field=models.IntegerField(blank=True, db_column='hesp_IdActividad', null=True),
        ),
        migrations.AddField(
            model_name='herramentalespecifico',
            name='hesp_IdChatarrizacion',
            field=models.IntegerField(blank=True, db_column='hesp_IdChatarrizacion', null=True),
        ),
        migrations.AddField(
            model_name='herramentalespecifico',
            name='hesp_IdDieSet',
            field=models.IntegerField(blank=True, db_column='hesp_IdDieSet', null=True),
        ),
        migrations.AddField(
            model_name='herramentalespecifico',
            name='hesp_IdEstadoHerr',
            field=models.IntegerField(blank=True, db_column='hesp_IdEstadoHerr', null=True),
        ),
        migrations.AddField(
            model_name='herramentalespecifico',
            name='hesp_IdFamilia',
            field=models.IntegerField(blank=True, db_column='hesp_IdFamilia', null=True),
        ),
        migrations.AddField(
            model_name='herramentalespecifico',
            name='hesp_IdHerramental',
            field=models.IntegerField(blank=True, db_column='hesp_IdHerramental', null=True),
        ),
        migrations.AddField(
            model_name='herramentalespecifico',
            name='hesp_IdImagen',
            field=models.IntegerField(blank=True, db_column='hesp_IdImagen', null=True),
        ),
        migrations.AddField(
            model_name='herramentalespecifico',
            name='hesp_IdManual',
            field=models.IntegerField(blank=True, db_column='hesp_IdManual', null=True),
        ),
        migrations.AddField(
            model_name='herramentalespecifico',
            name='hesp_IdMaquinaOpc',
            field=models.IntegerField(blank=True, db_column='hesp_IdMaquinaOpc', null=True),
        ),
        migrations.AddField(
            model_name='herramentalespecifico',
            name='hesp_IdMaquinaPP',
            field=models.IntegerField(blank=True, db_column='hesp_IdMaquinaPP', null=True),
        ),
        migrations.AddField(
            model_name='herramentalespecifico',
            name='hesp_IdOrdenProduccion',
            field=models.IntegerField(blank=True, db_column='hesp_IdOrdenProduccion', null=True),
        ),
        migrations.AddField(
            model_name='herramentalespecifico',
            name='hesp_IdPlano',
            field=models.IntegerField(blank=True, db_column='hesp_IdPlano', null=True),
        ),
        migrations.AddField(
            model_name='herramentalespecifico',
            name='hesp_IdPrestamo',
            field=models.IntegerField(blank=True, db_column='hesp_IdPrestamo', null=True),
        ),
        migrations.AddField(
            model_name='herramentalespecifico',
            name='hesp_IdPropiedadHerramental',
            field=models.IntegerField(blank=True, db_column='hesp_IdPropiedadHerramental', null=True),
        ),
        migrations.AddField(
            model_name='herramentalespecifico',
            name='hesp_IdTipoHerramental',
            field=models.IntegerField(blank=True, db_column='hesp_IdTipoHerramental', null=True),
        ),
        migrations.AddField(
            model_name='herramentalespecifico',
            name='estanteria',
            field=models.ForeignKey(blank=True, db_column='hesp_IdEstanteria', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='herramentales_especificos', to='herramental.estanteria'),
        ),
        migrations.AddField(
            model_name='estanteria',
            name='piso',
            field=models.ForeignKey(db_column='es_IdPiso', on_delete=django.db.models.deletion.PROTECT, related_name='estanterias', to='herramental.piso'),
        ),
        migrations.AddField(
            model_name='herramentalespecifico',
            name='piso',
            field=models.ForeignKey(blank=True, db_column='hesp_IdPiso', null=True, on_delete=django.db.models.deletion.PROTECT, to='herramental.piso'),
        ),
        migrations.CreateModel(
            name='UbicacionHerramental',
            fields=[
                ('uh_IdUbicacionHerr', models.AutoField(db_column='uh_IdUbicacionHerr', primary_key=True, serialize=False)),
                ('uh_NumeroFila', models.IntegerField(db_column='uh_NumeroFila')),
                ('uh_NumeroColumna', models.IntegerField(db_column='uh_NumeroColumna')),
                ('uh_NumeroPosicion', models.IntegerField(db_column='uh_NumeroPosicion')),
            ],
            options={
                'db_table': 'UBICACIONHERRAMENTAL',
                'unique_together': {('uh_NumeroFila', 'uh_NumeroColumna', 'uh_NumeroPosicion')},
            },
        ),
        migrations.AddField(
            model_name='herramentalespecifico',
            name='ubicacion_herr',
            field=models.ForeignKey(blank=True, db_column='hesp_IdUbicacionHerr', null=True, on_delete=django.db.models.deletion.PROTECT, to='herramental.ubicacionherramental'),
        ),
    ]
