# Generated by Django 5.2.7 on 2026-03-24 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramental', '0004_estanteria_piso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DieSet',
            fields=[
                ('di_IdDieSet', models.AutoField(db_column='di_IdDieSet', primary_key=True, serialize=False)),
                ('di_CodigoDieSet', models.CharField(db_column='di_CodigoDieSet', max_length=20, unique=True)),
                ('di_Dimensiones', models.CharField(blank=True, db_column='di_Dimensiones', max_length=50, null=True)),
                ('estanteria', models.ForeignKey(db_column='di_IdEstanteria', on_delete=django.db.models.deletion.PROTECT, to='herramental.estanteria')),
                ('piso', models.ForeignKey(db_column='di_IdPiso', on_delete=django.db.models.deletion.PROTECT, to='herramental.piso')),
                ('ubicacion', models.ForeignKey(db_column='di_IdUbicacionDieset', on_delete=django.db.models.deletion.PROTECT, to='herramental.ubicacionherramental')),
            ],
            options={
                'db_table': 'DIESET',
            },
        ),
    ]
