# Generated by Django 5.2.7 on 2025-12-29 21:06

import app.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('im_IdImagen', models.AutoField(primary_key=True, serialize=False)),
                ('im_FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('im_RutaRelativa', models.FileField(max_length=255, upload_to=app.documents.models.upload_to_path)),
                ('im_NombreImagen', models.CharField(max_length=60)),
                ('im_DescripcionImagen', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'IMAGEN',
                'managed': False,
            },
        ),
    ]
