# Generated by Django 5.2.7 on 2025-12-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccionForja',
            fields=[
                ('consecutivo_op', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('numero_pedido', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v_plantaVirtual',
                'managed': False,
            },
        ),
    ]
