# Generated by Django 5.2.7 on 2025-12-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipsl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenproduccionforja',
            options={'managed': False, 'ordering': ['-fecha_inicio']},
        ),
    ]
