# Generated by Django 5.2.7 on 2026-01-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estanteria',
            fields=[
                ('es_IdEstanteria', models.AutoField(db_column='es_IdEstanteria', primary_key=True, serialize=False)),
                ('es_NombreEstanteria', models.CharField(db_column='es_NombreEstanteria', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'ESTANTERIA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('pi_IdPiso', models.AutoField(db_column='pi_IdPiso', primary_key=True, serialize=False)),
                ('pi_NumeroPiso', models.CharField(db_column='pi_NumeroPiso', max_length=10, unique=True)),
                ('pi_DescripcionPiso', models.CharField(blank=True, db_column='pi_DescripcionPiso', max_length=255, null=True)),
            ],
            options={
                'db_table': 'PISO',
                'managed': False,
            },
        ),
    ]
