# Generated by Django 5.2.7 on 2025-12-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMaquina',
            fields=[
                ('id', models.AutoField(db_column='ea_IdEstadoMaquina', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='ea_NombreEstMaquina', max_length=30)),
            ],
            options={
                'db_table': 'ESTADOMAQUINA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(db_column='ma_IdMaquina', primary_key=True, serialize=False)),
                ('numero', models.IntegerField(db_column='ma_NumMaquina')),
                ('nombre', models.CharField(db_column='ma_NombreMaquina', max_length=30)),
                ('anio_instalacion', models.DateField(blank=True, db_column='ma_AnioInstalacion', null=True)),
                ('marca', models.CharField(blank=True, db_column='ma_Marca', max_length=30, null=True)),
                ('capacidad', models.FloatField(blank=True, db_column='ma_CapMaquina', null=True)),
                ('codigo', models.CharField(db_column='ma_CodigoMaquina', max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, db_column='ma_DescMaquina', null=True)),
            ],
            options={
                'db_table': 'MAQUINA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMaquina',
            fields=[
                ('id', models.AutoField(db_column='tm_IdTipoMaquina', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='tm_NombreTipoMaquina', max_length=30)),
                ('descripcion', models.CharField(blank=True, db_column='tm_Descripcion', max_length=500, null=True)),
            ],
            options={
                'db_table': 'TIPOMAQUINA',
                'managed': False,
            },
        ),
    ]
