# Generated by Django 5.2.7 on 2026-01-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(db_column='ac_IdActividad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='ac_NombreActividad', max_length=30)),
                ('fecha_creacion', models.DateTimeField(db_column='ac_FechaCreacionActivdad')),
                ('descripcion', models.CharField(db_column='ac_DescripcionActividad', max_length=500)),
            ],
            options={
                'db_table': 'ACTIVIDAD',
                'managed': False,
            },
        ),
    ]
